### ISSUE TITLE
API Error "invalid input syntax for type uuid" at /studysets/list-recent only when fetched immediately after /studysets/list

### ISSUE THREAD

**Issue by ehanahamed** [ehanahamed/quizfreely#32]
**Description**
The explore page works perfectly fine while a user is logged out. Both featured and recent sets are shown. When a user is logged in, goes home (dashboard) and then goes to explore, recent sets do not show. (but featured sets do) If the user reloads the page or navigates to it from a different page, like settings, recent sets show again.

Basic steps to reproduce this bug:
1. While logged out, open home/dashboard
2. From dashboard, navigate to explore
3. Explore shows featured and recents correctly
4. Reload explore
5. Explore shows featured and recents correctly
6. Log in
7. While logged in, open home/dashboard
8. From dashboard, navigate to explore
9. Explore shows featured correctly but fails to show recents
10. Reload explore
11. Explore shows featured and recents correctly

If the user waits before loading explore after being on dashboard, the bug doesn't happen:
1. While logged in, open home/dashboard
2. Wait 1 minute
3. Navigate to explore
4. Explore shows featured and recents correctly.
5. Reload explore
6. Explore shows featured and recents correctly
7. While logged in, open home/dashboard
8. Navigate to explore (without waiting)
9. Explore shows featured correctly but fails to show recents
10. Reload explore
11. Explore shows featured and recents

**Comment by ehanahamed** [comment]
After checking the logs for api:
```
{"level":50,"time":1727749003235,"pid":588697,"hostname":"quizfreely-api-quizfreely-web","reqId":"req-ad","err":{"type":"DatabaseError","message":"invalid input syntax for type uuid: \"\"","stack":"error: invalid input syntax for type uuid: \"\"\n    at /root/quizfreely/api/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.<anonymous> (file:///root/quizfreely/api/index.js:1064:22)","length":95,"name":"error","severity":"ERROR","code":"22P02","file":"uuid.c","line":"133","routine":"string_to_uuid"},"msg":"invalid input syntax for type uuid: \"\""}
{"level":50,"time":1727749023025,"pid":588697,"hostname":"quizfreely-api-quizfreely-web","reqId":"req-aj","err":{"type":"DatabaseError","message":"invalid input syntax for type uuid: \"\"","stack":"error: invalid input syntax for type uuid: \"\"\n    at /root/quizfreely/api/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.<anonymous> (file:///root/quizfreely/api/index.js:1064:22)","length":95,"name":"error","severity":"ERROR","code":"22P02","file":"uuid.c","line":"133","routine":"string_to_uuid"},"msg":"invalid input syntax for type uuid: \"\""}
{"level":50,"time":1727766820801,"pid":588697,"hostname":"quizfreely-api-quizfreely-web","reqId":"req-ay","err":{"type":"DatabaseError","message":"invalid input syntax for type uuid: \"dashboard.html\"","stack":"error: invalid input syntax for type uuid: \"dashboard.html\"\n    at /root/quizfreely/api/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.<anonymous> (file:///root/quizfreely/api/index.js:827:22)","length":146,"name":"error","severity":"ERROR","code":"22P02","where":"unnamed portal parameter $1 = '...'","file":"uuid.c","line":"133","routine":"string_to_uuid"},"msg":"invalid input syntax for type uuid: \"dashboard.html\""}
```

**Comment by ehanahamed** [comment]
I updated the API to retry those problematic queries once if they have an error the first time. This is a perfect workaround (for now).

That doesn't fix the actual source of the problem, so I will leave this issue open (for now).

The "problematic" API routes are `studysets/list-recent` and `studysets/search`. Both of these work perfectly fine normally. However, when run immediately after `studysets/list`, both of these cause a uuid syntax error from postgres. I still don't know why.

**Comment by ehanahamed** [comment]
The reason `/public/list/featured` works fine but `/public/list/recent` doesn't is because all featured sets are public. Row Level Security (RLS) only lets `quizfreely_api` select public studysets. Adding `where private = false` to search's and list-recent's queries solves this problem.
